### PR TITLE
bail out on bad config files, fixes #228

### LINKED ISSUE #228: [BUG] config.lua silently ignored when it fails
When the config file fails to load, it is silently ignored and defaults are used. This is ok if the file does not exist, but not ok if the file does exist but cannot be loaded due to a compilation error.

If the file fails to load, but does exist, a warning should be issued.

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

File: src/luarocks/persist.lua [hunk 1]
```diff
@@ -53,10 +53,10 @@ end
 -- @param filename string: the name of the file.
 -- @param tbl table or nil: if given, this table is used to store
 -- loaded values.
--- @return (table, table) or (nil, string, string): a table with the file's
--- assignments as fields and set of undefined globals accessed in file,
--- or nil, an error message and an error code ("open", "load" or "run") in
--- case of errors.
+-- @return table or (nil, string, string): a table with the file's assignments
```
Comment (mpeterv) [inline src/luarocks/persist.lua]: Why did you remove info on the second normal return value?

Comment (hishamhm) [inline src/luarocks/persist.lua]: My bad, that comment was lingering in the wrong function.
